Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:service}-users-${self:provider.stage}
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email

      # Customização de E-mails
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT

      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailSubject: Bem-vindo ao Korrige AI - Confirme seu cadastro
        EmailMessage: |
          <html>
            <head>
              <style>
                body { font-family: 'Segoe UI', Arial, sans-serif; background-color: #f5f5f5; margin: 0; padding: 0; }
                .container { max-width: 600px; margin: 40px auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
                .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 40px 30px; text-align: center; }
                .header h1 { margin: 0; font-size: 28px; font-weight: 600; }
                .content { padding: 40px 30px; }
                .code-box { background: #f8f9fa; border: 2px solid #667eea; border-radius: 8px; padding: 20px; margin: 30px 0; text-align: center; }
                .code { font-size: 32px; font-weight: 700; color: #667eea; letter-spacing: 4px; }
                .instructions { color: #666; line-height: 1.6; margin: 20px 0; }
                .footer { background: #f8f9fa; padding: 20px 30px; text-align: center; color: #999; font-size: 12px; }
              </style>
            </head>
            <body>
              <div class="container">
                <div class="header">
                  <h1>🎓 Korrige AI</h1>
                  <p style="margin: 10px 0 0 0; opacity: 0.9;">Bem-vindo à plataforma de correção de redações</p>
                </div>
                <div class="content">
                  <h2 style="color: #333; margin-top: 0;">Olá!</h2>
                  <p class="instructions">
                    Obrigado por se cadastrar no <strong>Korrige AI</strong>!
                    Para começar a usar nossa plataforma de correção de redações com IA,
                    confirme seu e-mail usando o código abaixo:
                  </p>
                  <div class="code-box">
                    <div style="color: #666; font-size: 14px; margin-bottom: 10px;">Seu código de verificação:</div>
                    <div class="code">{####}</div>
                  </div>
                  <p class="instructions">
                    Cole este código no app ou site para ativar sua conta.
                  </p>
                  <p class="instructions" style="font-size: 14px; color: #999;">
                    <strong>Importante:</strong> Este código expira em 24 horas.
                    Se você não solicitou este cadastro, ignore este e-mail.
                  </p>
                </div>
                <div class="footer">
                  <p>© 2025 Korrige AI. Todos os direitos reservados.</p>
                  <p>Este é um e-mail automático, não responda.</p>
                </div>
              </div>
            </body>
          </html>
        EmailSubjectByLink: Bem-vindo ao Korrige AI - Clique para confirmar
        EmailMessageByLink: |
          <html>
            <head>
              <style>
                body { font-family: 'Segoe UI', Arial, sans-serif; background-color: #f5f5f5; margin: 0; padding: 0; }
                .container { max-width: 600px; margin: 40px auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
                .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 40px 30px; text-align: center; }
                .header h1 { margin: 0; font-size: 28px; font-weight: 600; }
                .content { padding: 40px 30px; text-align: center; }
                .button { display: inline-block; background: #667eea; color: white; padding: 15px 40px; border-radius: 6px; text-decoration: none; margin: 20px 0; font-weight: 600; font-size: 16px; }
                .footer { background: #f8f9fa; padding: 20px 30px; text-align: center; color: #999; font-size: 12px; }
              </style>
            </head>
            <body>
              <div class="container">
                <div class="header">
                  <h1>🎓 Korrige AI</h1>
                  <p style="margin: 10px 0 0 0; opacity: 0.9;">Bem-vindo à plataforma de correção de redações</p>
                </div>
                <div class="content">
                  <h2 style="color: #333;">Confirme seu e-mail</h2>
                  <p style="color: #666; line-height: 1.6;">
                    Clique no botão abaixo para ativar sua conta no Korrige AI:
                  </p>
                  <a href="{##Clique aqui##}" class="button">Confirmar E-mail</a>
                  <p style="color: #999; font-size: 14px; margin-top: 30px;">
                    Se o botão não funcionar, copie e cole este link no navegador:<br/>
                    <span style="color: #667eea; word-break: break-all;">{##Link aqui##}</span>
                  </p>
                </div>
                <div class="footer">
                  <p>© 2025 Korrige AI. Todos os direitos reservados.</p>
                  <p>Este é um e-mail automático, não responda.</p>
                </div>
              </div>
            </body>
          </html>

      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
        - Name: name
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: phone_number
          AttributeDataType: String
          Required: false
          Mutable: true
      UserPoolTags:
        Environment: ${self:provider.stage}
        Service: ${self:service}

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:service}-client-${self:provider.stage}
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes
      ReadAttributes:
        - email
        - name
        - phone_number
      WriteAttributes:
        - email
        - name
        - phone_number

Outputs:
  UserPoolId:
    Description: ID do Cognito User Pool
    Value: !Ref UserPool
    Export:
      Name: ${self:service}-UserPoolId-${self:provider.stage}

  UserPoolClientId:
    Description: ID do Cognito User Pool Client
    Value: !Ref UserPoolClient
    Export:
      Name: ${self:service}-UserPoolClientId-${self:provider.stage}

  UserPoolArn:
    Description: ARN do Cognito User Pool
    Value: !GetAtt UserPool.Arn
    Export:
      Name: ${self:service}-UserPoolArn-${self:provider.stage}
